-- 코드를 입력하세요
SELECT A.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES*PRICE) AS TOTAL_SALES
FROM BOOK A 
    join AUTHOR B on A.AUTHOR_ID = B.AUTHOR_ID
    join BOOK_SALES C on A.BOOK_ID = C.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m-%d') LIKE ("2022-01%")
GROUP BY A.AUTHOR_ID, A.CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC